#!/usr/bin/env sh

set -e

DEBUG_MODE=

if [ "$1" = "debug" ]; then
    DEBUG_MODE=debug
fi

cd com.ingeint.scaleconnector.targetplatform
./plugin-builder $DEBUG_MODE ../com.ingeint.scaleconnector ../com.ingeint.scaleconnector.test
